jhipster-prod-postgresql:
  container_name: spedycja-prod-postgresql
  image: postgres:9.4.5
  # volumes:
  # - ~/volumes/jhipster/spedycja/prod-postgresql/:/var/lib/postgresql/
  environment:
  - POSTGRES_USER=spedycja
  - POSTGRES_PASSWORD=
  ports:
  - "5432:5432"

